name: todo_list
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-272.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.3.0
  firebase_auth: ^3.4.2
  firebase_core: ^1.20.0
  flutter_bloc: ^8.0.1
  sizer: ^2.0.15
  #hive: ^2.2.3
  #hive_flutter: ^1.1.0

  another_flushbar: ^1.10.29
  ordered_set: ^5.0.0

  #intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
     - family: Rubik
       fonts:
         - asset: fonts/Rubik/RubikMonoOne-Regular.ttf
     - family: Manrope
       fonts:
         - asset: fonts/Manrope/Manrope-Bold.ttf

